services:
  db:
    image: postgres:16
    container_name: erp_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: erp
      POSTGRES_USER: erp
      POSTGRES_PASSWORD: aM6AYeQ2xn25KhCE
    ports:
      - '5432:5432'
    volumes:
      - erp_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U erp -d erp']
      interval: 5s
      timeout: 5s
      retries: 20

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: erp_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: Welcome-123
    ports:
      - '5050:80'
    depends_on:
      db:
        condition: service_healthy

volumes:
  erp_db_data:
