name: api-e2e

on:
  pull_request:
  push:
    branches: ['master']

jobs:
  e2e:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: erp
          POSTGRES_PASSWORD: aM6AYeQ2xn25KhCE
          POSTGRES_DB: erp
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U erp -d erp"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=20

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install
        run: npm ci

      - name: Prettier check
        run: npm run format:check

      - name: Prisma generate (API)
        working-directory: apps/api
        run: npm run prisma:generate

      - name: Typecheck (API) - non blocking for now
        working-directory: apps/api
        run: npm run typecheck
        continue-on-error: true

      - name: Run API e2e (CI)
        working-directory: apps/api
        env:
          CI: 'true'
          DATABASE_URL: ${{ secrets.CI_DATABASE_URL }}
          SEED_ADMIN_EMAIL: ${{ secrets.SEED_ADMIN_EMAIL }}
          SEED_ADMIN_PASSWORD: ${{ secrets.SEED_ADMIN_PASSWORD }}
        run: npm run test:ci:e2e
